Change the style of Definitions
texmacs/texmacs pull request #46
Opened 2020-07-21 18:25 UTC by Iey4iej3

There are two reasons for such change:
1. Convention: most documents render Definitions roman instead of italic, but only italicize the terminology to be defined.
2. Coherence: there exists a macro `\dfn` in TeXmacs to underline the terminology. If I use that with definition environment, the effect is invisible. See the following TeXmacs Scheme code: `(definition (document (concat "An integer " (math "n") " is called " (dfn "non-negative") " if " (math "n<geq>0") ".")))`

2020-11-14 09:37 UTC, mgubi commented
I'm not sure about motivations. Definitions are necessary elements of the logic of a math document, at the level of theorems and lemmas. So I would tend to think they should have the same rendering. Remarks, exercise, etc.. can be ideally removed from the document and the "content" do not change. Maybe we should revise the macro \dfn instead. Also, you can create an additional package which provide your customisation. The problem in changing the global style is that this will break all the already existing documents, and this is bad...

2020-11-14 09:48 UTC, mgubi requested changes
I'm not sure this is appropriate, see my previous comment. Also, this is a large change that will break/modify a lot of documents. (e.g. it affects the numbering, probably)

2020-11-15 00:00 UTC, Iey4iej3 commented
It is unclear what should be correct. If you look at [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Theorems#Theorem_styles), you find three theorem styles: plain / definition / remark. We also have three in TeXmacs, but not accordingly: theorem / remark / exercise. It is very hard to tell which one is "correct", but at least for consistency, I suppose that `\dfn` should work both in definitions and elsewhere (I mean, new concepts informally mentioned in other paragraphs).

On the other hand, I don't know how this would affect numbering - I see that in US numbering style, there is only one counter group for theorems and remarks, and for European numbering style, all counters are separated.

2020-11-15 13:58 UTC, mgubi commented
I agree. `\dfn`should render in a distinctive way. However it does not seems to me acceptable to break old documents (i.e. change the rendering of all the definitions) for this reason. A different rendering of definitions can be obtained using another style if this is the intention of the author. For the `\dfn`problem I would suggest that prominency is obtained by rendering the content in 'roman' style in a context where the normal text is rendered as 'italic'. This probably can be obtained via \emph  (to be checked).

2020-11-16 11:44 UTC, Iey4iej3 commented
As for breaking old documents, I have recently noticed that Joris introduced several modifications (significant enough, for example, the rendering of all `\subsection*` is changed from bold to italic) which makes `amsart` more similar to the rendering in LaTeX. In view of that, it might be OK to at least redefine `definition` environment in `amsart`?

2020-11-16 13:20 UTC, mgubi commented
The situation is as follows: each developer has his own "domain", Joris, by definition is competent in all domains. I'm not and anyway I will ask him before modifying parts of the code in which I'm not expert. As for standard styles, I think the easies modification is just to add something which does not substantially modify old documents. If you think that amsart is not properly defined, this is a bug and we certainly have to correct it. Can you resume the status of the PR? What you want to change and why we need to change it (compared to the modification just being a customisation which is suitable for you)?

2020-11-16 13:48 UTC, Iey4iej3 commented
I close this PR and will open a bug later. The behavior of `\dfn` should be considered a bug, and the rendering style of definitions is just different from that in LaTeX (and conventions), but not a bug strictly speaking.

2020-11-16 13:48 UTC, closed without merging

2020-11-16 13:58 UTC, mgubi commented
Thanks for taking care of this. As for bug/non bug, I tend to think that if we do not reproduce the "amsart" style properly then this is a bug since the name clearly is associated to the particular style used by AMS. For the generic style I tend to think that we are not obliged to conform to LaTeX.  For this purpose we could define "Latex-compatible" styles "latex-article" if there is some pressure etc...

2020-11-16 22:16 UTC, Iey4iej3 commented
I believe that this rendering (only italicizing the terms defined, but italicizing the propositions, theorems and corollaries, etc) has a much longer history than that of LaTeX. I randomly picked up some old textbooks or articles: Atiyah-Macdonald (1969), Eilenberg-Steenrod (1952), Steenrod's The Topology of fibre bundles (1951), they render things like this.

Furthermore, there are mimeographed books and papers: usually they underline instead of italicize. An example: [Joyal's paper](https://maths-people.anu.edu.au/~borger/classes/copenhagen-2016/references/joyal1.pdf) and [Quillen's unpublished notes](math.uchicago.edu/~amathew/cotangent.djvu).

I guess that this might be a very old tradition, at least in mathematics: if you look at [Goursat's Cours d'analyse mathématique (1910)](https://archive.org/details/ed2coursdanalyse01gouruoft/), it was already with similar renderings.

I will open a bug on `\dfn` soon.

2020-11-17 12:17 UTC, Iey4iej3 commented
Reference to two bugs: https://savannah.gnu.org/bugs/?59471 and https://savannah.gnu.org/bugs/?59472